
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'Project_C'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'Project_C'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/
# directory as views. These settings can be overridden in the individual model
# files using the `{{ config(...) }}` macro.
models:

  Project_C:

    staging:
      +materialized: view
      +schema: staging

    intermediate:
      +materialized: view
      +schema: core

    dimensions:
      +materialized: table
      +schema: core

    facts:
      +materialized: table
      +schema: core

    marts:
      +materialized: table
      +schema: marts

seeds:
  Project_C:
    +schema: reference

vars:
  analysis_start_date: '2024-01-01'

on-run-start:
  - "{{ log('DBT RUN STARTED', info=True) }}"

on-run-end:
  - "{{ log('DBT RUN COMPLETED', info=True) }}"
